"""Export steps: writing into the Godot project.

The studio copies into the Godot project what Godot opens natively: an entity's
mesh (glTF, with the animations the agent put in it). Sprite sheets stay in the
library (`3d/<entity>/sprites/`).

A game's Godot project is its folder: the studio exports there if it holds a
`project.godot`, and never creates one -- otherwise a game whose Godot project
lives in `client/` would get a second project at its root (`godot_target`).
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from ...store.folders import ProjectPaths
from ..base import Context, Step, StepResult


def _res_path(project_root: Path, target: Path) -> str:
    """`res://` path of a file, relative to the Godot project root."""
    return "res://" + target.relative_to(project_root).as_posix()


class ExportGodotMesh(Step):
    """Copy an entity's mesh into the Godot project, with its animations.

    Godot imports glTF natively: no conversion, no plugin. The animations the
    file carries land in the `AnimationPlayer` generated on import; a bare mesh
    arrives as is.
    """

    name = "export_godot_mesh"

    def __init__(self, character_id: str, mesh_asset_id: str, *,
                 godot_project: Path, subdir: str = "characters") -> None:
        self.character_id = character_id
        self.mesh_asset_id = mesh_asset_id
        self.godot_project = Path(godot_project)
        self.subdir = subdir

    def inputs(self) -> dict[str, Any]:
        return {"character": self.character_id, "mesh": self.mesh_asset_id,
                "project": str(self.godot_project)}

    def run(self, ctx: Context) -> StepResult:
        source = ctx.store.path_for(self.mesh_asset_id)
        if source is None:
            raise RuntimeError(f"mesh {self.mesh_asset_id} not found")
        root = self.godot_project
        target = root / self.subdir / self.character_id / f"{self.character_id}{source.suffix}"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        return StepResult(data={"mesh": str(target), "res_path": _res_path(root, target)},
                          assets=[])


def godot_target(paths: ProjectPaths, target: Path | None = None) -> Path:
    """The Godot project to export to: `target`, otherwise the project folder.

    A folder that already holds a `project.godot` is taken as is. Otherwise the
    studio creates one only in the folder of a project it hosts itself
    (`data/projects/<project>/`, with no game behind it); anywhere else -- a
    game's folder, a path given by hand -- it refuses.
    """
    target = Path(target) if target is not None else paths.godot
    if (target / "project.godot").is_file():
        return target
    if paths.linked or target.resolve() != paths.godot.resolve():
        raise ValueError(
            f"no project.godot in {target}: the studio does not create one in a game folder -- "
            "create the Godot project there, or point to the folder that holds it")
    return create_godot_project(target, paths.project)


def create_godot_project(path: Path, name: str) -> Path:
    """Write a minimal project.godot if the folder has none.

    Only in a folder the studio owns: a hosted project (see `godot_target`) or
    a throwaway validation project.
    """
    path.mkdir(parents=True, exist_ok=True)
    project_file = path / "project.godot"
    if not project_file.exists():
        project_file.write_text(
            "; Generated by gamestudio.\n"
            "config_version=5\n\n"
            "[application]\n"
            f'config/name="{name}"\n'
            'config/features=PackedStringArray("4.4")\n\n'
            "[rendering]\n"
            'textures/canvas_textures/default_texture_filter=0\n',
            encoding="utf-8",
        )
    return path
