"""The code map: what lives where in the repository, one line per file.

Every file opens with a sentence saying what it is for; the map gathers them,
so a development session starts from it instead of exploring the repository.

It is written to `context/codemap.md`, versioned, and imported by `CLAUDE.md`:
an arriving agent knows it without looking for it. Like the skills index, it is
regenerated (`gamestudio context codemap`) and `make check` refuses a stale map.

The map holds only paths and opening sentences -- no size, no date: it changes
only when a file appears, disappears or changes purpose, which is exactly when
it must be reread.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Any

from .context import studio

CODEMAP = "codemap.md"

# The repository's zones, in the order an agent needs them. Each pattern is
# relative to the root; a missing folder is skipped.
ZONES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    ("Python — `src/gamestudio/`", "src/gamestudio", ("**/*.py",)),
    ("React front — `app/src/`", "app/src", ("**/*.ts", "**/*.tsx")),
    ("Tauri shell — `app/src-tauri/src/`", "app/src-tauri/src", ("*.rs",)),
    ("Scripts — `scripts/`", "scripts", ("*.py",)),
)

# Beyond this, an opening sentence is no longer a summary: it is cut.
MAX_SUMMARY = 140

_JS_BLOCK = re.compile(r"^\s*/\*\*?(.*?)\*/", re.S)


def root() -> Path:
    """The repository root: where `CLAUDE.md` and `context/` live."""
    settings = studio().settings
    return settings.project_root or Path.cwd()


def path() -> Path:
    return studio().settings.context_path / CODEMAP


def _first_sentence(text: str) -> str:
    """The header's first paragraph, folded into one line."""
    paragraph = text.strip().split("\n\n", 1)[0]
    line = " ".join(part.strip() for part in paragraph.splitlines()).strip()
    if len(line) > MAX_SUMMARY:
        line = line[:MAX_SUMMARY - 1].rstrip() + "…"
    return line


def _python_summary(file: Path) -> str:
    try:
        doc = ast.get_docstring(ast.parse(file.read_text(encoding="utf-8")))
    except (SyntaxError, UnicodeDecodeError):
        return ""
    return _first_sentence(doc or "")


def _js_summary(file: Path) -> str:
    text = file.read_text(encoding="utf-8", errors="replace")
    match = _JS_BLOCK.match(text)
    if not match:
        return ""
    body = "\n".join(line.strip().lstrip("*").strip()
                     for line in match.group(1).splitlines())
    return _first_sentence(body)


def _rust_summary(file: Path) -> str:
    lines: list[str] = []
    for line in file.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("//!"):
            lines.append(stripped[3:].strip())
        elif lines or stripped:
            break
    return _first_sentence("\n".join(lines))


def _summary(file: Path) -> str:
    if file.suffix == ".py":
        return _python_summary(file)
    if file.suffix == ".rs":
        return _rust_summary(file)
    return _js_summary(file)


def entries() -> list[dict[str, Any]]:
    """The repository's zones, each with its files and their opening sentence.

    An `__init__.py` without a docstring is a mere re-export point: it teaches
    nothing and stays off the map.
    """
    base = root()
    zones: list[dict[str, Any]] = []
    for title, folder, patterns in ZONES:
        directory = base / folder
        if not directory.is_dir():
            continue
        files = sorted({f for pattern in patterns for f in directory.glob(pattern)
                        if f.is_file() and "__pycache__" not in f.parts
                        and "node_modules" not in f.parts})
        rows = []
        for file in files:
            summary = _summary(file)
            if file.name == "__init__.py" and not summary:
                continue
            rows.append({"path": file.relative_to(base).as_posix(),
                         "summary": summary})
        zones.append({"title": title, "folder": folder, "files": rows})
    return zones


def render(zones: list[dict[str, Any]]) -> str:
    lines = [
        "# Code map",
        "",
        "<!-- Regenerated by `gamestudio context codemap`: do not edit by hand. -->",
        "",
        "One file per line, with the sentence that opens its header. This is where",
        "a change starts: open the relevant file directly, without exploring the",
        "repository again. A file without a summary is a header to write.",
        "",
    ]
    for zone in zones:
        lines += [f"## {zone['title']}", ""]
        for row in zone["files"]:
            summary = row["summary"] or "*(no header)*"
            lines.append(f"- `{row['path']}` — {summary}")
        lines.append("")
    return "\n".join(lines)


def codemap() -> dict[str, Any]:
    """The map as it should be, and where it is written."""
    zones = entries()
    return {"path": str(path()), "files": sum(len(z["files"]) for z in zones),
            "markdown": render(zones)}


def write() -> dict[str, Any]:
    """Rewrite `context/codemap.md` from the files."""
    data = codemap()
    target = path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(data["markdown"], encoding="utf-8")
    return {**data, "written": True}


def check() -> dict[str, Any]:
    """Is the written map the one the files give?

    This is what `make check` runs: a drifting map would send an agent to a
    file that no longer exists, or hide a new one from it.
    """
    data = codemap()
    target = path()
    current = target.read_text(encoding="utf-8") if target.is_file() else None
    problem = ("map missing" if current is None
               else "map out of date" if current != data["markdown"] else None)
    return {"path": data["path"], "files": data["files"], "ok": problem is None,
            "problem": problem}
