//! The manifest of the application's commands, for the windows' capabilities.
//!
//! Declaring its commands puts the application under Tauri's access control: a
//! window can only call those its capability grants (`allow-<command>` in
//! `capabilities/`). Without this manifest, any window could call all of them:
//! read the clipboard, run `make`.
//!
//! The list follows `generate_handler!` in `src/lib.rs`. Each command's
//! permissions are generated in `permissions/autogenerated/`, and versioned
//! with it.

const COMMANDS: &[&str] = &[
    "api_auth",
    "update_status",
    "update_build",
    "update_progress",
    "update_now",
    "update_skip",
    "show_chat",
    "set_language",
    "toggle_studio",
    "chat_pinned",
    "toggle_chat_pin",
    "clipboard_read",
    "clipboard_write",
];

fn main() {
    let manifest = tauri_build::AppManifest::new().commands(COMMANDS);
    if let Err(error) =
        tauri_build::try_build(tauri_build::Attributes::new().app_manifest(manifest))
    {
        panic!("{error:#}");
    }
}
